In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [3]:
df.shape

(569, 33)

Droping `id` and `Unnamed: 32` columns beacuse they are not required

In [4]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

# Scaling 

All teh values of dataframe are on different scale, it is best to scale them so that all the values lies within a range

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 0.19879942,  0.19514297,  0.16007094, ..., -0.17180604,
        -0.83502121, -0.95975516],
       [ 0.81121281,  0.37817702,  0.79553776, ...,  1.05952523,
        -0.41719064, -0.41021939],
       [ 1.21109918, -0.42809956,  1.18054635, ...,  0.81021865,
        -0.60307589,  0.60422364],
       ...,
       [-0.36048221, -0.73161172, -0.39677307, ..., -0.83915719,
         1.19655654, -0.7053201 ],
       [-0.71003323, -0.27518504, -0.63993639, ...,  0.43473862,
        -0.35632556,  0.50805488],
       [ 0.41971567,  0.88789209,  0.73069421, ...,  2.02482814,
         0.65864082,  1.01362779]], shape=(455, 30))

In [9]:
pd.DataFrame(y_train)

diagnosis
495         B
335         M
498         M
481         B
294         B
..        ...
8           M
151         B
268         B
469         B
258         M

[455 rows x 1 columns]

As the labels are Letters not numbers, and our neural network only understand numbers, so we have to convert the labels to some numbers. For that we'll use `Label Encoder`

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [11]:
y_train

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,

## Numpy arrays to Pytorch tensors

All the the dataframes (X_train, X_test, y_train & y_test) are based on numoy arrays. But as we have build the model in pytorch, so we have to convert them into Pytorch **tensors**

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining The Model

For starting we'll be creating a very simple Neuron, which have only weights and biases.

As our training dataset have 30 input features, so neuron will get 30 inputs. For our usecase these 30 values will be random.

In [14]:
# Take the one index value of X_train shape, this actually indicates the
# total columns in X_train 
torch.rand(X_train_tensor.shape[1],1)

tensor([[0.4722],
        [0.8210],
        [0.8996],
        [0.3116],
        [0.5536],
        [0.8402],
        [0.8453],
        [0.3583],
        [0.6937],
        [0.9224],
        [0.8488],
        [0.9264],
        [0.7599],
        [0.1996],
        [0.1989],
        [0.3037],
        [0.4611],
        [0.4929],
        [0.6091],
        [0.6317],
        [0.1273],
        [0.0743],
        [0.3761],
        [0.7528],
        [0.2201],
        [0.0641],
        [0.4401],
        [0.8847],
        [0.3706],
        [0.9145]])

In [15]:
from torch import nn

class SimpleANN(nn.Module):

    def __init__(self, X):
        self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
        

    def forward(self,X):
      z = torch.matmul(X, self.weights) + self.bias
      y_pred = torch.sigmoid(z)
      return y_pred
    
    def loss_function(self, y_pred, y):
       # Calulate predictions to aviod log(0)
       epsilon = 1e-7
       y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)

       # Calculate Loss
       loss = -(y_train_tensor * torch.log(y_pred) + (1- y_train_tensor) * torch.log(1-y_pred)).mean()
       return loss


### Important Parameters

In [16]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

Training Pipeline Contains Following Steps
- Creating Model
- Forward Pass
- Calculate Loss
- Backpropagation
- Parameter Update

All these steps happen in loop and loop runs for defined number of time as we have defined in `epochs`.
We'll each of these steps in detail

In [17]:
# create Model
model = SimpleANN(X_train_tensor)

# define loop
for epoch in range(epochs):

    # forward pass
    y_pred = model.forward(X_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred, y_test)
    
    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -=learning_rate * model.weights.grad
        model.bias -=learning_rate * model.bias.grad

    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_() 

    # print loss iin each epoch
    print(f'Epoch: {epoch}, Loss: {loss.item()}')

Epoch: 0, Loss: 4.07422749562199
Epoch: 1, Loss: 3.96428829296112
Epoch: 2, Loss: 3.85365248027674
Epoch: 3, Loss: 3.7387357068952483
Epoch: 4, Loss: 3.621711607133174
Epoch: 5, Loss: 3.5016487923476625
Epoch: 6, Loss: 3.3749254108594338
Epoch: 7, Loss: 3.2392815881427093
Epoch: 8, Loss: 3.0975068344406425
Epoch: 9, Loss: 2.947948551527434
Epoch: 10, Loss: 2.7915238370932665
Epoch: 11, Loss: 2.6292571959818054
Epoch: 12, Loss: 2.463351766677791
Epoch: 13, Loss: 2.2941425263924478
Epoch: 14, Loss: 2.121857826224562
Epoch: 15, Loss: 1.9488489328349057
Epoch: 16, Loss: 1.7760635502401165
Epoch: 17, Loss: 1.6125757832245189
Epoch: 18, Loss: 1.4583314972183636
Epoch: 19, Loss: 1.319260643002042
Epoch: 20, Loss: 1.1973361831954066
Epoch: 21, Loss: 1.0939281999002581
Epoch: 22, Loss: 1.0095406669050686
Epoch: 23, Loss: 0.9436182078430307
Epoch: 24, Loss: 0.8944182333961542


## Model Evaluation

In [18]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy : {accuracy.item()}')

Accuracy : 0.5240073800086975
